### ISSUE TITLE
[stable/concourse] Address PR backlog and add more maintainers

### ISSUE THREAD

**Issue by william-tran** [helm/charts#10617]
The list of PRs has been growing and the current maintainers haven't had the time to address them. Thankfully, members of the Concourse team have expressed interest in taking on the job, and the opportunity is there for others to join the maintainer list. This issue is to track the priority of outstanding PRs so we can work at serializing the changes and make the merging process as smooth as possible. I'd like to get to PR 0 by the end of the week as have at least one more maintainer added.

Here's the list of PRs outstanding in the order I want to merge them into, which will be updated in place. Contributors, please make note of the chart version your change is assigned to (I'm going to fill that out as we go along). You can also propose any changes to the priority in comments.

- [x] #9207 Limit emptyDir size (@richardalberto) *(Chart v3.1.0)*
- [x] #9204 Fix AWS SSM Syntax Error (@Jeeppler)  *(Chart v3.1.1)*
- [x] #9665 Improves use of TLS certs (@cirocosta) *(Chart v3.2.0)*
- [x] #9906 make web probes configurable (@cirocosta) *(Chart v3.4.0, what happened to 3.3.0? misbump, oh well)*
- [x] #9614 Adds imagepullSecrets support (@cirocosta) *(Chart v3.5.0)*
- [x] #10624 Revert Moves prometheus annotation to deployment *(Chart v3.5.1)*
- [x] #9364 Specify secrets mount path (@goddenrich) *(Chart v3.6.0)*
- [ ] #9525 Generate random password to local user by default (@cirocosta) *(bump patch)*
- [ ] #9949 Fix key names in example (@Eronarn)  *(bump patch)*
- [ ] #10237 Allow AWS role based authentication to Secrets Manager and Systems Manager (@tareks)  *(bump minor)*
- [x] ~~#9536 Moves prometheus annotation to deployment (@cirocosta)~~
- [ ] #9668 Replaces worker StatefulSet by Deployment (@cirocosta)

**Comment by cirocosta** [comment]
Thanks a lot for putting effort and time on this @william-tran !

I just wanted to point out to everyone that the Concourse team wants a lot to gather feedback from the community and having members actively participating in the discussions around having a great experience for people operating Concourse on top of K8S.

Besides the usual issues that can be created both in this repository and the [Concourse repository](https://github.com/concourse/concourse), feel free to join us on Discord (https://concourse-ci.org/community.html#section_discord)! There's a specific channel for Kubernetes discussions there 👍

**Comment by william-tran** [comment]
@cirocosta since you might be the only one online right now with outstanding PRs, wdyt about knocking out #9614, #9525, and #9906?

**Comment by william-tran** [comment]
@cirocosta I've reordered the PRs in the list and assigned versions to the ones that are already in LGTM status, if you set the version and rebase I *think* everything else is automatic

**Comment by william-tran** [comment]
@paulczar Please acknowledge that you won't be slapping every mergable PR with LGTM and let those who are actually using and maintaining this chart do their job.

**Comment by william-tran** [comment]
acknowledged in https://github.com/helm/charts/pull/9536#issuecomment-454194256 and over slack. That's it for today.

**Comment by tareks** [comment]
Thanks @william-tran for the effort to get this sorted! Appreciate that you guys are under a lot of load, but you can consider that as a measure of great success :) 

Hopefully the extra hands will help get fixes/features out more efficiently.

**Comment by cirocosta** [comment]
Hey @william-tran ,

With https://github.com/helm/charts/pull/10766, I'd say we can get rid of both #9525 and #9949 

Thanks!

**Comment by goddenrich** [comment]
Hey I think #9364 Specify secrets mount path (@goddenrich) (Chart v3.6.0) is blocked because there's a hold tag
