### ISSUE TITLE
[stable/kibana] Migration Tracker

### ISSUE THREAD

**Issue by compleatang** [helm/charts#14935]
In collaboration with the team at elastic, @monotek and I the maintainers of the kibana chart have decided to put the chart into a "pre-depreaction" status. Given that the [elasticsearch chart](https://github.com/helm/charts/tree/master/stable/elasticsearch#pre-deprecation-notice) is moving over it makes sense to move Kibana over too.

`Old Chart`: https://github.com/helm/charts/tree/master/stable/kibana
`New Chart`: https://github.com/elastic/helm-charts/tree/master/kibana

This issue should operate as the central tracking issue for work that has been and will be accomplished in this migration path.

## General

- [ ] Add a pre-migration notice to stable/kibana's README
- [ ] Close off all issues that deal with v7.X upgrades and refer them to this issue and/or the elastic charts for their improvements to the stable/kibana chart
- [ ] Decide a deadline for "actually" deprecating the chart and follow the procedures [here](https://github.com/helm/charts/blob/master/stable/kibana/templates/volume-claim.yaml)
- [ ] Finalize whether elastic/kibana needs a migration guide similar to [elastics](https://github.com/elastic/helm-charts/blob/master/elasticsearch/examples/migration/README.md) ... my early view is that there is no need due to the relatively stateless positioning of stable/kibana

## Specific Functionality 

The below functionality of the stable/kibana chart should ideally be migrated to elastic/kibana:

- [ ] PVCs for plugins ([whole file](https://github.com/helm/charts/blob/master/stable/kibana/templates/volume-claim.yaml))
- [ ] Service Account flexibility ([whole file](https://github.com/helm/charts/blob/master/stable/kibana/templates/serviceaccount.yaml) rather than [simple invocation](https://github.com/elastic/helm-charts/blob/e6771f4b8b26c163433bd171e490d28dd77de75c/kibana/templates/deployment.yaml#L35)
- [ ] Services:
  - Labels
  - loadBalancerSourceRanges
  - clusterIP (ability to customize)
  - loadBalancerIP
  - customizable selectors
  - non-cluster-IP service types
  - authProxyEnabled functionality
- [ ] Ingress:
  - allow path element in ingress values from (#9028)
- [ ] Dashboard import feature
- [ ] Deployments
  - deployment annotations
  - revisionHistoryLimit
  - podAnnotations
  - podLabels
  - init containers work
  - pullPolicy
  - commandline.args
  - envFromSecrets
  - authProxyEnabled
  - probes flexibility (timing mostly)
  - extraVolumeMounts
  - extraContainers
  - extraConfigMapMounts
  - extraVolumes
  - dashboardImport.enabled
  - plugins.enabled

## Test functionality

It's unclear to me at this time what we should do with the tests because it appears that the helm-elastic repo has it's own python based test runner. 

cc @monotek @crazybus @jethr0null if I missed anything.

**Comment by compleatang** [comment]
not stale. still actionable.

**Comment by monotek** [comment]
pr to add dashboard import: https://github.com/elastic/helm-charts/pull/244

**Comment by monotek** [comment]
Not stale.

**Comment by monotek** [comment]
Not stale.

**Comment by monotek** [comment]
@compleatang 
Imho we can deprecate the chart. 

Im pretty sure we'll see PRs pretty soon, if some of the features are needed in the official chart. 
To be honest, i don't even use Kibana at the moment, as we switched to Stackdriver at work and Im i also thinking about to try out Loki for a private project, so i lost a bit of interest in EFK stack.

**Comment by compleatang** [comment]
actually, same, we've moved to stackdriver as well.

**Comment by monotek** [comment]
I've added a pr to deprecate the chart: https://github.com/helm/charts/pull/23844

**Comment by compleatang** [comment]
:+1:
