### ISSUE TITLE
[stable/*] bump dependency postgresql 0.8.1

### ISSUE THREAD

**Issue by scottrigby** [helm/charts#1951]
## PRs to review
- [x] stable/concourse #1945 
- [x] stable/gitlab-ce #1946
- [x] stable/gitlab-ee #1947
- [x] stable/odoo #1948 
- [x] stable/redmine #1949
- [x] ~stable/sentry #1950~ outdated

## Background
PRs opened using my dependency version bump utility script. See:
- https://github.com/kubernetes/helm/issues/1947
- https://github.com/kubernetes/helm/pull/2041
- https://github.com/kubernetes/helm/issues/2205

**Comment by scottrigby** [comment]
Just waiting on a retest of https://github.com/kubernetes/charts/pull/1950

**Comment by scottrigby** [comment]
✅
