### ISSUE TITLE
[stable/several] Transition from stable to bitnami 

### ISSUE THREAD

**Issue by carrodher** [helm/charts#20969]
**Context**
With the Helm 3 release, there are some changes affecting the charts repository. Some changes are due to technical reasons, while others are to facilitate the maintenance of the charts. 

About the second item, in the next months `stable`/`incubator` are going to be de-listed from Hubs (in fact, they are already not included by default in Helm 3). [Here](https://github.com/helm/community/blob/master/proposals/distributed-search.md) you can find more information about the distributed approach to maintain charts.
That means each chart maintainer should move the charts to their own repository, and of course, maintain them, provide support, include them in [Kubeapps Hub](https://hub.kubeapps.com/), etc

Given the [`stable` deprecation timeline](https://github.com/helm/charts#deprecation-timeline), from Bitnami we are going to start moving the charts maintained by us to https://github.com/bitnami/charts.

This repository is already included in the Hubs and we will provide the same cadence of updates, support, etc that we've been keeping here these years. Installation instructions are very similar, just adding the _bitnami_ repo and using it during the installation (`bitnami/<chart>` instead of `stable/<chart>`)

```bash
$ helm repo add bitnami https://charts.bitnami.com/bitnami
$ helm install my-release bitnami/<chart>           # Helm 3
$ helm install --name my-release bitnami/<chart>    # Helm 2
```

After the migration takes place, issues/PRs related to the charts itself will be redirected to `bitnami/charts`, we'll be happy to answer questions related to this migration in this Issue, k8s Slack, etc.

**Action plan** 
- [Deprecate the charts from _stable_ repo](https://github.com/helm/charts/blob/master/PROCESSES.md#deprecating-a-chart).
- Add a note in each chart README pointing to the new location.
- Update this issue so users can have a commonplace to see the reason, process, feel comfortable with the move, (comment if they feel like it), etc.

**Affected charts**
- [x] [dokuwiki](https://github.com/helm/charts/tree/master/stable/dokuwiki)
- [x] [drupal](https://github.com/helm/charts/tree/master/stable/drupal)
- [x] [external-dns](https://github.com/helm/charts/tree/master/stable/external-dns)
- [x] [ghost](https://github.com/helm/charts/tree/master/stable/ghost)
- [x] [jasperreports](https://github.com/helm/charts/tree/master/stable/jasperreports)
- [x] [joomla](https://github.com/helm/charts/tree/master/stable/joomla)
- [x] [kubewatch](https://github.com/helm/charts/tree/master/stable/kubewatch)
- [x] [mariadb](https://github.com/helm/charts/tree/master/stable/mariadb)
- [x] [mediawiki](https://github.com/helm/charts/tree/master/stable/mediawiki)
- [x] [mongodb](https://github.com/helm/charts/tree/master/stable/mongodb)
- [x] [moodle](https://github.com/helm/charts/tree/master/stable/moodle)
- [x] [nats](https://github.com/helm/charts/tree/master/stable/nats)
- [x] [odoo](https://github.com/helm/charts/tree/master/stable/odoo)
- [x] [opencart](https://github.com/helm/charts/tree/master/stable/opencart)
- [x] [orangehrm](https://github.com/helm/charts/tree/master/stable/orangehrm)
- [x] [osclass](https://github.com/helm/charts/tree/master/stable/osclass)
- [x] [owncloud](https://github.com/helm/charts/tree/master/stable/owncloud)
- [x] [parse](https://github.com/helm/charts/tree/master/stable/parse)
- [x] [phabricator](https://github.com/helm/charts/tree/master/stable/phabricator)
- [x] [phpbb](https://github.com/helm/charts/tree/master/stable/phpbb)
- [x] [phpmyadmin](https://github.com/helm/charts/tree/master/stable/phpmyadmin)
- [x] [postgresql](https://github.com/helm/charts/tree/master/stable/postgresql)
- [x] [prestashop](https://github.com/helm/charts/tree/master/stable/prestashop)
- [x] [rabbitmq](https://github.com/helm/charts/tree/master/stable/rabbitmq)
- [x] [redis](https://github.com/helm/charts/tree/master/stable/redis)
- [x] [redmine](https://github.com/helm/charts/tree/master/stable/redmine)
- [x] [suitecrm](https://github.com/helm/charts/tree/master/stable/suitecrm)
- [x] [testlink](https://github.com/helm/charts/tree/master/stable/testlink)
- [x] [wordpress](https://github.com/helm/charts/tree/master/stable/wordpress)

**Comment by scottrigby** [comment]
This is complete, and users appear to have transitioned without trouble. Thanks @carrodher for all your work on this! 💯
