### ISSUE TITLE
[stable/*] helm repo migration

### ISSUE THREAD

**Issue by scottrigby** [helm/charts#21103]
Given the stable and incubator [support plan](https://github.com/helm/charts/blob/master/README.md#status-of-the-project) and [Deprecation Timeline](https://github.com/helm/charts/blob/master/README.md#deprecation-timeline), the community (chart OWNERS, organizations, groups or individuals who want to host charts) are moving charts to new Helm repos, and will list these new repos on the [Helm Hub](https://hub.helm.sh/) before stable and incubator are de-listed there. This issue is to help the community track this migration.

**To-do:** we will update this issue soon with migration that has already finished, what is in progress, and what's left to do.

**List in progress**
- [x] bitnami charts (https://github.com/helm/charts/issues/20969)
- [x] jaeger (https://github.com/jaegertracing/helm-charts)
- [x] kong(https://github.com/kong/charts)
- [ ] nginx-ingress (WIP: https://github.com/kubernetes/ingress-nginx/issues/5161)
- [ ] prometheus charts
    - [x] propose via mailing list (https://groups.google.com/forum/#!topic/prometheus-users/oHU4bktoqKs)
- [x] influxdata charts (https://github.com/influxdata/helm-charts)
- [ ] fluent charts (https://github.com/fluent/helm-charts)
    - [x] advisory issue created https://github.com/helm/charts/issues/21235
    - [x] repo up Chart was revamped and re created from scratch
    - [x] Add to helm hub
    - [ ] Deprecate old chart with migration path

**Comment by mitsos1os** [comment]
Hi everyone,

Just a clarification regarding the stable repo deprecation.

In case I am using the latest available version of the charts in the stable repo and do not want to use any upgrades from the new migrated repositories, will I still be able to use them after final deprecation of stable repo? This includes manually adding the repo to Helm 3 `helm repo add stable https://kubernetes-charts.storage.googleapis.com`

Or will this also stop being available and I have to switch to the new repos no matter what?

Thanks!

**Comment by sudermanjr** [comment]
Are there any plans to migrate the stable/k8s-spot-termination-handler chart to another repo?

@axozoid 
@egeland 
@KierranM 
@mariusv

**Comment by mariusv** [comment]
@sudermanjr I don't mind taking it

**Comment by pierluigilenoci** [comment]
@hareku 
@mariusv 
@srueg 
any plan to migrate efs-provisioner? https://github.com/helm/charts/tree/master/stable/efs-provisioner

Moreover, even https://github.com/kubernetes-retired/external-storage/tree/master/aws/efs is retired and archived. 😞 

There are alternatives?

**Comment by pierluigilenoci** [comment]
@olemarkus 
@kennethaasan
any plan to migrate metrics-server? https://github.com/helm/charts/tree/master/stable/metrics-server

**Comment by pierluigilenoci** [comment]
@jstriebel 
any plan to migrate kube-slack? https://github.com/helm/charts/tree/master/stable/kube-slack

**Comment by pierluigilenoci** [comment]
@desaintmartin 
@miouge1
any plan to migrate oauth2-proxy? https://github.com/helm/charts/tree/master/stable/oauth2-proxy

**Comment by olemarkus** [comment]
> @olemarkus
> @kennethaasan
> any plan to migrate metrics-server? https://github.com/helm/charts/tree/master/stable/metrics-server

Currently tracked in https://github.com/kubernetes-sigs/metrics-server/issues/572

**Comment by desaintmartin** [comment]
oauth2-proxy: discussions here https://github.com/oauth2-proxy/oauth2-proxy/issues/608

**Comment by pierluigilenoci** [comment]
@verwilst 
@davidkarlsen
any plan to migrate nfs-client-provisioner? https://github.com/helm/charts/tree/master/stable/nfs-client-provisioner

**Comment by pierluigilenoci** [comment]
@hareku
@mariusv
@srueg
I was suggested to migrate to https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner
Ref: https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/issues/91
So I presume that efs-provisioner will be not supported.

**Comment by mariusv** [comment]
> @hareku
> @mariusv
> @srueg
> I was suggested to migrate to https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner
> Ref: [kubernetes-sigs/sig-storage-lib-external-provisioner#91](https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/issues/91)
> So I presume that efs-provisioner will be not supported.

@pierluigilenoci that is bad news :-(

**Comment by JoshKCarroll** [comment]
@scottrigby I saw you mentioned in another ticket that you had written up instructions for migrating a chart out of this repo into a new home (e.g. maintaining commit history and exposing it on artifact hub, i'm guessing). Looking through this issue and the repo I'm not finding those readily. Is it something you can share a link to?

@verwilst has agreed to pick up and maintain the Bookstack chart (https://github.com/BookStackApp/BookStack/issues/2322#issuecomment-710660621) and hoping to get them off to a good start :)

**Comment by verwilst** [comment]
nfs-client-provisioner and rocketchat are others i currently maintain, i'm willing to keep maintaining them in the future too.

**Comment by torstenwalter** [comment]
@JoshKCarroll while migrating some charts I wrote this guide: https://github.com/torstenwalter/helm-chart-hosting

**Comment by thesuperzapper** [comment]
Can someone please confirm if this repo is still being archived, I am really unclear after the latest blog post: https://helm.sh/blog/new-location-stable-incubator-charts/

Do the existing OWNERS still need to move their charts?

**Comment by pierluigilenoci** [comment]
@thesuperzapper confirmed. OWNERS still need to move their charts.

**Comment by thesuperzapper** [comment]
@pierluigilenoci then what are all those blog posts about, just the legacy versions?

**Comment by pierluigilenoci** [comment]
@thesuperzapper 
@mattfarina quote from https://kubernetes.slack.com/archives/C6E3XH1ED/p1603120675041800

> There are two things. Being deprecated and being available. At Nov 13th the plan is still to deprecate the stable and incubator chart repos. The new location allows them to be accessible even after deprecation where we stop updating them.
> We are working to find the charts new homes after the deprecation. Those will be discoverable on the artifact hub
> Many of them have already moved but more than a few have not. I think we are talking about this situation on the Helm dev call this week.

**Comment by torstenwalter** [comment]
@thesuperzapper I think this post explains it https://helm.sh/blog/new-location-stable-incubator-charts/
There are new locations for stable and incubator repositories hosting the already published charts.

> Important Note: This does not affect the obsolescence timeline for the stable and incubator repositories that was announced in 2019. On November 13, 2020 the stable and incubator charts repository will reach the end of development and become archives. You can find that many of the charts have moved to other, community managed, repositories. You can discover these on the Artifact Hub. More information on the obsolescence will follow in future blog posts and communications.

**Comment by chadlwilson** [comment]
@verwilst Do you have any idea when/where `nfs-client-provisioner` is likely to move? Do you know perhaps if K8s `sig-storage` plan to host a repo for the charts related to various such provisioners? (with/without the deprecated `efs-provisioner`)

**Comment by pierluigilenoci** [comment]
@chadlwilson https://github.com/helm/charts/issues/21103#issuecomment-703465166 :(

**Comment by desaintmartin** [comment]
Legal question here! Would that be okay to move from Apache 2 to MIT? oauth2-proxy is licenced under MIT and I suppose it would be easier to match destination licence.

**Comment by scottrigby** [comment]
> Legal question here! Would that be okay to move from Apache 2 to MIT? oauth2-proxy is licenced under MIT and I suppose it would be easier to match destination licence.

@desaintmartin I have opened a CNCF service desk issue for this question. Let's wait to see where that goes.

**Comment by pierluigilenoci** [comment]
@scottrigby oauth2-proxy status is missing from the table.

> oauth2-proxy: discussions here [oauth2-proxy/oauth2-proxy#608](https://github.com/oauth2-proxy/oauth2-proxy/issues/608)

**Comment by canterberry** [comment]
I've relocated stable/docker-registry to twuni/docker-registry and published this repo and chart to Artifact Hub for the community to use. I hope that's okay. Happy to defer to an "official" chart if/when the time comes. Just bridging the gap as best I can, since a migration for it doesn't appear to have been picked up, yet.

# Links

 * Source: https://github.com/twuni/docker-registry.helm
 * Artifact Hub: https://artifacthub.io/packages/helm/twuni/docker-registry

**Comment by pierluigilenoci** [comment]
@tcarmet @miniscruff @alexanderchan-scality any plan to migrate the redis-ha chart somewhere?

**Comment by DandyDeveloper** [comment]
@pierluigilenoci Redis-ha has been migrated to: https://github.com/DandyDeveloper/charts/tree/master/charts/redis-ha (Per the deprecation message in the chart itself).

Thank you for asking!

**Comment by pierluigilenoci** [comment]
> @pierluigilenoci Redis-ha has been migrated to: [DandyDeveloper/charts@`master`/charts/redis-ha](https://github.com/DandyDeveloper/charts/tree/master/charts/redis-ha) (Per the deprecation message in the chart itself).

Thank you @DandyDeveloper 
@scottrigby the table need to be update 😄

**Comment by scottrigby** [comment]
Hi everyone. I have been dealing with a family emergency the past few weeks. 

We will want to update the table/list above to help people find the new home(s) for these charts. But we'll need to find a different way to determine this moving forward since this repo code will no longer be updated, notices will no longer be added to each charts readme as it was before.

Generally speaking, Charts are now discoverable in the CNCF Artifact Hub (https://artifacthub.io/).

Maintainers of distributed chart repos are encouraged to:
- list their repos in the Artifact Hub
- follow the [Charts Best Practices Guide](https://helm.sh/docs/chart_best_practices/)
- for greater reliability, integrate automated [Helm Chart Testing](https://github.com/helm/chart-testing) (though [Helm chart repo GitHub Actions](https://github.com/helm/charts-repo-actions-demo) or otherwise)
- when releasing charts (whether using [Helm Chart Releaser](https://github.com/helm/chart-releaser), the wrapping [GitHub Action](https://github.com/helm/chart-releaser-action), or otherwise), ensure versioned packages are immutable (any changes, however small, should be a new version). For greater community reliability, please continue to follow [Semantic Versioning](https://semver.org/)
- when adopting chart source code for new development, please carry over git history. @torstenwalter compiled a good step-by-step guide based on work I and he had done on this for various community chart repos: https://github.com/torstenwalter/helm-chart-hosting. Please follow that as best as you can.
- The Artifact Hub allows you to verify chart repo ownership, and there is also a process for marking a chart "official" there. Official charts are maintained (or approved) by the maintainers of the application the chart installs. This doesn't mean other charts are bad to use - for example, Bitnami had for years maintained many of the community charts in this repo, and now continue to do so now in their own distributed chart repo, and are still equally trustworthy. This is just to help users navigate, and make up their own minds about the trustworthiness of each chart repo and chart. As always, users are encouraged to review a chart's code before installing it.

If anyone has other ideas about how this issue can be more useful to end users and maintainers alike, please let me know and we can do whatever we need to to help the community. The charts maintainers who formerly managed this repo are still active in working on tools to help the wider Helm charts community. Thank you all for the continued community.

**Comment by pierluigilenoci** [comment]
@scottrigby thanks so much for the explanation and for your time!

IMHO, beside continuing to keep this issue open by updating the table, I see no other way to give more information to the community.

At the end, if all the charts that have not migrated within the dealine remain without precise indications, it is to be attributed to the maintainers who have not acted before. For the charts I use I tried to push the maintainers but more than asking, it couldn't be done. So that's okay too.

**Comment by mrueg** [comment]
Quick update here, 

stable/coredns is Done via https://github.com/coredns/helm/
stable/kube-state-metrics is Done via https://github.com/kubernetes/kube-state-metrics/tree/master/charts/kube-state-metrics

**Comment by verwilst** [comment]
I've done Rocketchat, https://github.com/verwilst/helm-charts/tree/main/charts/rocketchat

Kind regards,

Bart
________________________________

**Comment by austince** [comment]
`minio` is actually now hosted at https://helm.min.io

**Comment by desaintmartin** [comment]
I've done `clamav`, https://artifacthub.io/packages/search?page=1&ts_query_web=clamav

**Comment by vasiliyb** [comment]
Folks, any plans to fix `stable/openvpn`?  Thanks

**Comment by desaintmartin** [comment]
> Folks, any plans to fix `stable/openvpn`? Thanks

There are several charts at https://artifacthub.io/packages/search?page=1&ts_query_web=openvpn, maybe there's one that fits your needs.

If you need the original stable/openvpn, you could try hosting it and publishing it in the Artifact Hub ! ;)


BTW, not sure if this is still relevant to post it here, but I moved/updated stable/karma as well: https://artifacthub.io/packages/search?page=1&ts_query_web=karma

**Comment by travisgroth** [comment]
stable/pomerium was officially done under https://github.com/helm/charts/pull/24378.
