### ISSUE TITLE
[stable/incubator] relocate package history

### ISSUE THREAD

**Issue by scottrigby** [helm/charts#23850]
## Problem

Once the stable/incubator chart repos are marked obsolete, and this git repo is archived, the package history from these repos are planned to be garbage collected. Users who are not able to upgrade to newer versions will fail when attempting to pull/install/upgrade etc previous versions.

## Status

The Helm team is working on an official recommendation. Subscribe to this issue for updates.

## Solution Timeline
- [x]  Archive Chart tarballs and re-index to new backup charts repo in GH Pages (https://github.com/helm/charts/issues/21103)
- [x] Add repo archive notice to all non-deprecated charts (#24030)
- [x]  Mark all charts as deprecated (https://github.com/helm/charts/issues/24310) 
- [x] Create a redirect via index.yaml in the GCS buckets to point to GH Pages archive
     Users shouldn't see any failures at this point but will be pointing at the new archive location.
- [x]  Create a chart that [has a known-missing required field](https://github.com/viglesiasce/deprecation-chart/blob/main/templates/NOTES.txt#L10) -  https://github.com/viglesiasce/deprecation-chart
- [x] Replace all existing tarball urls in the GCS index.yaml to point to the deprecation chart. 
    This will give users an error message pointing them in the right direction to fix their issues.

## Additional context 
- See the stable and incubator [support plan](https://github.com/helm/charts/blob/master/README.md#status-of-the-project) and [Deprecation Timeline](https://github.com/helm/charts/blob/master/README.md#deprecation-timeline)
- Issue tracking stable charts new locations: https://github.com/helm/charts/issues/21103

**Comment by viglesiasce** [comment]
Another option that shuts down the repos but at least gives users one final pointer would be to:

1. Create a chart with a required field that would most definitely not be set in any chart:
   ```
    {{ required "This repo has been shut down. Please read our guidance here:https://github.com/helm/charts#deprecation-timeline!" .Values.thisRepoHasBeenShutDown}}
   ```
 1. Edit the index.yaml to point all chart's `urls` fields to the location of that chart:
   ```yaml
   urls:
    - https://kubernetes-charts.storage.googleapis.com/deletion-notice-1.0.0.tgz
   ```

The behavior would be that when someone try's to install and or upgrade an existing chart they would get a hard failure that would print out the error message that we crafted and point them at more details on what they can do to fix.

There would still be costs involved here however so we'd want to continue to optimize in that dimension where possible.

**Comment by paulczar** [comment]
from Helm Call, I would love to deprecate every chart on Nov 13 ( as in set deprecated: true )   and we should set warnings in NOTES.txt in all charts ASAP to mention the chart repo url is moving and the chart will be deprecated and no changes accepted as of Nov 13.

**Comment by viglesiasce** [comment]
> from Helm Call, I would love to deprecate every chart on Nov 13 ( as in set deprecated: true ) and we should set warnings in NOTES.txt in all charts ASAP to mention the chart repo url is moving and the chart will be deprecated and no changes accepted as of Nov 13.

I added this to the solution timeline.

**Comment by scottrigby** [comment]
See updates:
- https://helm.sh/blog/new-location-stable-incubator-charts/
- https://helm.sh/blog/charts-repo-deprecation/

**Comment by viglesiasce** [comment]
```Create a redirect via index.yaml in the GCS buckets to point to GH Pages archive
Users shouldn't see any failures at this point but will be pointing at the new archive location.```

This was done today.

**Comment by viglesiasce** [comment]
Objects in the legacy buckets have now been marked private.
