### ISSUE TITLE
[stable/*] bump dependency postgresql 0.8.3

### ISSUE THREAD

**Issue by scottrigby** [helm/charts#2400]
## PRs to review
- [x] stable/concourse #2391 
- [ ] ~stable/gitlab-ce #2403~ Chart deprecated
- [ ] ~stable/gitlab-ee #2397~ Chart deprecated
- [x] stable/odoo #2398
- [ ] ~stable/redmine #2399~ Outdated

## Background
PRs opened using my dependency version bump utility script. See:
- https://github.com/kubernetes/helm/issues/1947
- https://github.com/kubernetes/helm/pull/2041
- https://github.com/kubernetes/helm/issues/2205

**Comment by scottrigby** [comment]
All the `[stable/*] bump dependency postgresql 0.8.3` PRs listed in this issue are either merged or closed. Now that stable/postgresql is [0.8.4](https://github.com/kubernetes/charts/blob/master/stable/postgresql/Chart.yaml) I'll do another full automated set of version bump PRs this weekend or coming week.
